services:
  web:
    image: jorlar88/jornlarsen:${GIT_COMMIT_HASH:-latest} #use for live build -> docker io
    networks:
      - proxy
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.entrypoints=http"
      - "traefik.http.routers.web.rule=Host(`cvjorn.jotunutvikling.dev`)"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.web.middlewares=redirect-to-https"
      - "traefik.http.routers.web.entrypoints=https"
      - "traefik.http.routers.web.rule=Host(`cvjorn.jotunutvikling.dev`)"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=cloudflare"
    deploy:
      update_config:
        order: start-first
networks:
  proxy:
    external: true
